# Generated by Django 2.2.4 on 2021-02-26 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tv_show_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='New_show',
            new_name='Show',
        ),
    ]
