# Generated by Django 2.2.4 on 2021-02-26 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tv_show_app', '0003_auto_20210226_1532'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='all_shows',
            name='actions',
        ),
    ]
