# Generated by Django 2.2.4 on 2021-02-26 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tv_show_app', '0004_remove_all_shows_actions'),
    ]

    operations = [
        migrations.DeleteModel(
            name='All_shows',
        ),
    ]
